<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Deal extends Model
{
    use HasFactory;

    protected $fillable = [
        'title', 'value', 'stage', 'notes', 'lead_id', 'client_id', 'created_by'
    ];

    protected $casts = [
        'value' => 'float',
    ];

    // Related lead
    public function lead(): BelongsTo
    {
        return $this->belongsTo(Lead::class);
    }

    // Client who owns this deal
    public function client(): BelongsTo
    {
        return $this->belongsTo(User::class, 'client_id');
    }

    // Commercial or admin who created the deal
    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    // Revenue generated by this deal (1:1)
    public function revenue(): HasOne
    {
        return $this->hasOne(Revenue::class);
    }
}
